### ISSUE TITLE
setFullscreen not work

### ISSUE THREAD

**Issue by ittoh0819** [Meqn/UnityWebGL.js#3]
Thank you for your great plugin!

Almost works properly.
But setFullscreen() is not working on My environment(Unity2020.3.24f1).

VueCode:
Unity.setFullScreen(true);

Error:
"TypeError: Unity.setFullScreen is not a function"

Please, Can you help me ?

ittoh0819

**Comment by Meqn** [comment]
Can you find the `setFullscreen` method on `Unity` object ? Please print the `Unity` on the console.
